services:
  # backend:
  #   build:
  #     context: ./forum-backend
  #   # image: forum-wedkarskie-backend
  #   container_name: forum_backend
  #   env_file:
  #     - .env
  #   # volumes:
  #   #   - ./forum-backend:/app
  #   #   - ~/.m2:/root/.m2
  #   ports:
  #     - 8080:8080
  #     # - 35729:35729
  #     # - 5005:5005
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./forum-backend/
  #         target: /app/
  #   #     - action: restart
  #   #       path: ./backend/pom.xml
  #   depends_on:
  #     - postgres
  #   networks:
  #     - forum_net
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: forum_frontend
  #   ports:
  #     - "80:80"
  #     - "5173:5173"

  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
  #   networks:
  #     - forum_net
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # networks:
    #   - forum_net
volumes:
  postgres_data:

networks:
  forum_net: