spring:
  config:
    import: file:../.env[.properties]
  application:
    name: forum-backend
  datasource:
    url: jdbc:postgresql://forum_postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS
  devtools:
    restart:
      # poll-interval: 2s
      # quiet-period: 1s
      enabled: true
#      enabled: false
    livereload:
      enabled: true
  docker:
    compose:
      enabled: true
      file: ../docker-compose.yaml


forum:
  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER}
      expirySeconds: ${JWT_EXPIRY}
    cookies:
      name: ${COOKIE_NAME}
      domain: ${COOKIE_DOMAIN}
      expiresAfterSeconds: ${JWT_EXPIRY}
  files:
    main_folder: user-files
    defaultFolder: default
  constants:
    comments:
      pageSize: 20
  api:
    prefix: /api