spring:
  config:
    import: file:../.env[.properties]
  application:
    name: forum-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:forum_dev}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  devtools:
    restart:
      # poll-interval: 2s
      # quiet-period: 1s
      enabled: true
#      enabled: false
    livereload:
      enabled: true
  docker:
    compose:
      enabled: true
      file: ../docker-compose.yaml


forum:
  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: ${JWT_ISSUER}
      expirySeconds: ${JWT_EXPIRY}
    cookies:
      name: ${COOKIE_NAME}
      domain: ${COOKIE_DOMAIN}
      expiresAfterSeconds: ${JWT_EXPIRY}
  files:
    default:
      folders:
        main: resources
        user_files: user-files
        default-user: default-user
        fish: fish
        spots: spots
        content: content
    fish:
      defaultPhoto: fish.jpg
  constants:
    pagination:
      default_size: 20
      default_page: 0
    comments:
      pageSize: 20
  api:
    prefix: /api
    tomtom_key: ${TOMTOM_API_KEY}
    tomtom_minimum_precision: 80